{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "329833f2",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "from datetime import date\n",
    "from nsepy import get_history"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "3c1e6e2f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-15 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-29 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-25 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-7 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-5 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-21 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-31 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-27 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-47 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-9 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "Exception in thread Thread-17 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread     return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "Thread-13 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-11 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-52 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-39 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-35 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-23 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "Exception in thread Thread-45 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-19 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-43 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-49 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-33 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-41 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-51 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-50 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-48 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-46 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-44 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-42 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-40 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-38 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-37 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 143, in get_history_quanta\n",
      "    df = url_to_df(url=url,\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 167, in __call__\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in send\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 725, in <listcomp>\n",
      "    history = [resp for resp in gen]\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/requests/sessions.py\", line 191, in resolve_redirects\n",
      "    raise TooManyRedirects(\n",
      "requests.exceptions.TooManyRedirects: Exceeded 30 redirects.\n",
      "Exception in thread Thread-36 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-34 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-32 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-30 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-28 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-26 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-24 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-22 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-20 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-18 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-16 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-14 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-12 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-10 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n",
      "Exception in thread Thread-8 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-6 (get_history):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/varmor/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py\", line 136, in get_history\n",
      "    return pd.concat((t1.result, t2.result))\n",
      "                      ^^^^^^^^^\n",
      "AttributeError: 'ThreadReturns' object has no attribute 'result'\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "'ThreadReturns' object has no attribute 'result'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[5], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m sbin \u001b[38;5;241m=\u001b[39m get_history(symbol\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mSBIN\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[1;32m      2\u001b[0m                    start\u001b[38;5;241m=\u001b[39mdate(\u001b[38;5;241m2015\u001b[39m,\u001b[38;5;241m1\u001b[39m,\u001b[38;5;241m1\u001b[39m),\n\u001b[1;32m      3\u001b[0m                    end\u001b[38;5;241m=\u001b[39mdate(\u001b[38;5;241m2023\u001b[39m,\u001b[38;5;241m9\u001b[39m,\u001b[38;5;241m10\u001b[39m))\n",
      "File \u001b[0;32m~/miniconda3/envs/dp/lib/python3.11/site-packages/nsepy/history.py:136\u001b[0m, in \u001b[0;36mget_history\u001b[0;34m(symbol, start, end, index, futures, option_type, expiry_date, strike_price, series)\u001b[0m\n\u001b[1;32m    134\u001b[0m     t1\u001b[38;5;241m.\u001b[39mjoin()\n\u001b[1;32m    135\u001b[0m     t2\u001b[38;5;241m.\u001b[39mjoin()\n\u001b[0;32m--> 136\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m pd\u001b[38;5;241m.\u001b[39mconcat((t1\u001b[38;5;241m.\u001b[39mresult, t2\u001b[38;5;241m.\u001b[39mresult))\n\u001b[1;32m    137\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    138\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m get_history_quanta(\u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'ThreadReturns' object has no attribute 'result'"
     ]
    }
   ],
   "source": [
    "sbin = get_history(symbol='SBIN',\n",
    "                   start=\"2015,1,1\",\n",
    "                   end=\"2023,9,10\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "09deaa9f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
